//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinApp.ExtControl.Languages {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinApp.ExtControl.Languages.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 箭头 的本地化字符串。
        /// </summary>
        public static string Arrow {
            get {
                return ResourceManager.GetString("Arrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清空 的本地化字符串。
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭 的本地化字符串。
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 完成 的本地化字符串。
        /// </summary>
        public static string Complete {
            get {
                return ResourceManager.GetString("Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 椭圆 的本地化字符串。
        /// </summary>
        public static string Ellipse {
            get {
                return ResourceManager.GetString("Ellipse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 跳至 的本地化字符串。
        /// </summary>
        public static string Goto {
            get {
                return ResourceManager.GetString("Goto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 画笔 的本地化字符串。
        /// </summary>
        public static string Ink {
            get {
                return ResourceManager.GetString("Ink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 条 的本地化字符串。
        /// </summary>
        public static string Items {
            get {
                return ResourceManager.GetString("Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最大化 的本地化字符串。
        /// </summary>
        public static string Maximize {
            get {
                return ResourceManager.GetString("Maximize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最小化 的本地化字符串。
        /// </summary>
        public static string Minimize {
            get {
                return ResourceManager.GetString("Minimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 否 的本地化字符串。
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 页 的本地化字符串。
        /// </summary>
        public static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 方框 的本地化字符串。
        /// </summary>
        public static string Rectangle {
            get {
                return ResourceManager.GetString("Rectangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更换 的本地化字符串。
        /// </summary>
        public static string Replace {
            get {
                return ResourceManager.GetString("Replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 向下还原 的本地化字符串。
        /// </summary>
        public static string Restore {
            get {
                return ResourceManager.GetString("Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 的本地化字符串。
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择 的本地化字符串。
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全选 的本地化字符串。
        /// </summary>
        public static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文字 的本地化字符串。
        /// </summary>
        public static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 共 的本地化字符串。
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是 的本地化字符串。
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
